include(util)

find_package(PkgConfig REQUIRED QUIET)

checkSetParam(PETSC_DIR TRUE)
checkSetParam(PETSC_ARCH TRUE)

list(APPEND CMAKE_PREFIX_PATH "${PETSC_DIR}/${PETSC_ARCH}")

if(PETSC_FIND_REQUIRED)
  set(_PETSC_OPTS "REQUIRED")
endif()
if(PETSC_FIND_QUIETLY)
  set(_PETSC_OPTS "QUIET")
endif()
if(PETSC_FIND_REQUIRED AND PETSC_FIND_QUIETLY)
  set(_PETSC_OPTS "REQUIRED QUIET")
endif()

pkg_check_modules(PETSC ${_PETSC_OPTS} IMPORTED_TARGET PETSc)

if(PETSC_FOUND)
  set(PETSC_INCLUDE_DIRS "${PETSC_STATIC_INCLUDE_DIRS}")
  set(PETSC_LIBRARIES "${PETSC_STATIC_LDFLAGS};${PETSC_STATIC_LIBRARIES}")
endif(PETSC_FOUND)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(PETSC DEFAULT_MSG PETSC_LIBRARIES PETSC_INCLUDE_DIRS)
mark_as_advanced(PETSC_LIBRARIES PETSC_INCLUDE_DIRS)
